//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::{DbBackend, DbConn, EntityTrait, query::*, Schema, sea_query};

pub async fn setup_schema<E: EntityTrait>(db: &DbConn, entity: E) {
    // Setup Schema helper
    let schema = Schema::new(DbBackend::Sqlite);

    // Derive from Entity
    let stmt: sea_query::TableCreateStatement = schema.create_table_from_entity(entity);

    // Execute create table statement
    let _ = db.execute(db.get_database_backend().build(&stmt)).await;
}
